### ISSUE TITLE
Code.gov Browse Projects should include all federal agencies that completed OSS inventory

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-harvester-deprecated#18]
In addition to the CFO Act agencies (24), the Browse Projects should list all Federal agencies. For example, it should include projects from CFPB which has published a code.json file. 

https://code.gov/#/explore-code/agencies/CFPB

**Comment by froi** [comment]
Following up with this after our talk.

It was decided that the front-end will not display the agencies that have no repos to show. This will only affect the __browse by project_ section.

This change should not affect the API endpoint that shows all agencies.

Future development for this will happen here and in [code-gov-api](https:github.com/GSA/code-gov-api).

**Comment by froi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Code.gov Browse Projects should include all federal agencies that completed OSS inventory](https://trello.com/c/bSgnULVm/570-codegov-browse-projects-should-include-all-federal-agencies-that-completed-oss-inventory)

**Comment by froi** [comment]
This has been resolved both here and in the harvester found in the API.
