### ISSUE TITLE
Add repo topics

### ISSUE THREAD

**Issue by jbjonesjr** [GSA/code-gov-harvester-deprecated#2]
It would be awesome if this repo could include a `code-gov` topic to make it easily discoverable along other code.gov related utilities on GitHub.com.

Topics are now an even more prominent part of the discovery experience of GitHub.com (https://github.com/topics), and are being used to help users discover projects they may be interested in (https://github.com/updates). Creating a centralized place for code.gov repositories may also help in reducing duplication of effort as well.

Also, that would then make them more easily searchable on https://code.gov... how meta.

**Comment by froi** [comment]
I like it! I'll definitely add it.

> Also, that would then make them more easily searchable on https://code.gov... how meta

HA! Excellent point! 😄

**Comment by jbjonesjr** [comment]
for reference: https://help.github.com/articles/about-topics/

**Comment by froi** [comment]
Done and done. Thanks for the suggestion @jbjonesjr 

![image](https://user-images.githubusercontent.com/1918027/31866536-06bc6ea2-b74f-11e7-9fd1-f1103eb082c6.png)
